version: '3.1'
services:
  dis_task:
    image: osasergey/dis_task
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=dis
    volumes:
      - dev_db_volume:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  dev_db_volume:
